##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Tue Jan 25 12:40:38 2022
##  Generated by MIG Version 4.1
##  
##################################################################################################
##  File name :       example_top.sdc
##  Details :     Constraints file
##                    FPGA Family:       ZYNQ
##                    FPGA Part:         XC7Z020ICLG400_PKG
##                    Speedgrade:        -1
##                    Design Entry:      VERILOG
##                    Frequency:         400 MHz
##                    Time Period:       2500 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->Components->MT41J128M8XX-125
## Data Width: 16
## Time Period: 2500
## Data Mask: 1
##################################################################################################

set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_ck_n[*]} ]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_ck_p[*]} ]
          
create_clock -period 2.5 [get_ports sys_clk_p]
          
create_clock -period 5 [get_ports clk_ref_p]
          
############## NET - IOSTANDARD ##################


